# -*- coding: utf-8 -*-
"""tic tac.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vrSN79taq0LhA_OflOqL8oZ0gDLbNvWG

1-draw a board
2-input player name
3-put sign to each player
4-if user doesn't input between (1-9),direct them to previous sate
5-put sign to exact spot after taking user input
6-print board after each input
7-calculate and display result
"""

sign_dictionary = [' '] * 9

def print_board():
    board = f"""
     {sign_dictionary[0]} | {sign_dictionary[1]} | {sign_dictionary[2]}
    ---|---|---
     {sign_dictionary[3]} | {sign_dictionary[4]} | {sign_dictionary[5]}
    ---|---|---
     {sign_dictionary[6]} | {sign_dictionary[7]} | {sign_dictionary[8]}
    """
    print(board)

index_list = []

def take_input(player_name):
    while True:
        x = int(input(f"{player_name}: ")) - 1
        if 0 <= x < 9:
            if x in index_list:
                print("This spot is blocked.")
                continue
            index_list.append(x)
            return x
        print("Please enter a number between 1-9")

def calculate_result(player_one, player_two):
    winning_combinations = [(0, 1, 2), (0, 4, 8), (2, 5, 8), (3, 4, 5),
                            (1, 4, 7), (2, 4, 6), (6, 7, 8), (0, 3, 6)]

    for combo in winning_combinations:
        if all(sign_dictionary[i] == 'X' for i in combo):
            print(f"Congratulations {player_one}! You WON")
            return True
        elif all(sign_dictionary[i] == '0' for i in combo):
            print(f"Congratulations {player_two}! You WON")
            return True
    return False

def main():
    print("Welcome to the tic-tac-toe game!")
    player_one = input("Enter player one name: ")
    player_two = input("Enter player two name: ")
    print(f"Thank you for joining {player_one} and {player_two}")
    print(f"{player_one}'s sign will be - X")
    print(f"{player_two}'s sign will be - 0")
    input("Enter any key to start the game: ")

    print_board()

    for i in range(9):
        if i % 2 == 0:
            index = take_input(player_one)
            sign_dictionary[index] = 'X'
        else:
            index = take_input(player_two)
            sign_dictionary[index] = '0'

        print_board()
        if calculate_result(player_one, player_two):
            return

    print("This is a TIE, Nobody Won. Play Again.")

if __name__ == "__main__":
    main()